---
- name: Install and configure apache 2
  hosts: all

  tasks:
    - name: Instal apache2
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Ensure apache2 is running
      service:
        name: apache2
        state: started
        enabled: yes 
