---
- name: Install and configure apache 2
  hosts: all

  tasks:
    - name: Instal apache2 and mysql-server
      apt:
        name: "{{ item }}" 
        state: present
      loop:
        - apache2
        - mysql-server

    - name: Récupérer les package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Print the package facts
      ansible.builtin.debug:
        var: ansible_facts.packages

    - name: Modifier le fichier index.html quand Apache2 est installé
      copy:
        dest: "/var/www/index.html"
        content: "Bonjour depuis Ansible"
        mode: '0644'
      when: 
      when: "'apache2' in ansible_facts.packages"    
